table Years
	lineageTag: cfefab0d-6f57-4176-8d50-5388d0597c70

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 540c64f4-1a51-4278-8896-614368a77afd
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Time Drill' = 'Years'[Decade]
		dataType: string
		lineageTag: 6f310ebc-0a02-4f22-b966-27efe708d813
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column YearEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4eb78352-2fe1-4d4c-8901-4ec3b7c98462
		summarizeBy: none
		sourceColumn: YearEndDate

		variation Variation
			isDefault
			relationship: bb73e54f-017b-4bd6-9075-f67cf4d53684
			defaultHierarchy: LocalDateTable_65aec1b2-082a-4e97-b25a-b2baa9a88433.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Decade
		dataType: string
		lineageTag: fd714604-0547-4afe-8802-8fe8ea9382eb
		summarizeBy: none
		sourceColumn: Decade

		annotation SummarizationSetBy = Automatic

	column FiveYearBand
		dataType: string
		lineageTag: 6d0ebff9-a9c6-463c-97cf-b2590117e197
		summarizeBy: none
		sourceColumn: FiveYearBand

		annotation SummarizationSetBy = Automatic

	column IsLatestYear
		dataType: int64
		formatString: 0
		lineageTag: 28a34a5f-67f6-4fe1-a648-bb40b462a864
		summarizeBy: sum
		sourceColumn: IsLatestYear

		annotation SummarizationSetBy = Automatic

	column IsLast10Years
		dataType: int64
		formatString: 0
		lineageTag: ad9642bc-b91b-4971-9d07-fb426186ed7f
		summarizeBy: sum
		sourceColumn: IsLast10Years

		annotation SummarizationSetBy = Automatic

	column IsLast5Years
		dataType: string
		lineageTag: 1ed1d9f5-4f91-4b9d-9009-007333282946
		summarizeBy: none
		sourceColumn: IsLast5Years

		annotation SummarizationSetBy = Automatic

	column EconomicEra
		dataType: string
		lineageTag: b0503273-8d20-4d43-a4b4-9c7cba3d0e6f
		summarizeBy: none
		sourceColumn: EconomicEra

		annotation SummarizationSetBy = Automatic

	partition Years = m
		mode: import
		source =
				let
				                StartYear = 1990,
				                EndYear = 2024,
				                Count = EndYear - StartYear + 1,
				                YearList = List.Numbers(StartYear, Count),
				                #"Converted to Table" = Table.FromList(YearList, Splitter.SplitByNothing(), {"Year"}, null),
				                #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table", {{"Year", Int64.Type}}),
				                #"Added YearEndDate" = Table.AddColumn(#"Changed Type", "YearEndDate", each #date([Year], 12, 31), type date),
				                #"Added Decade" = Table.AddColumn(#"Added YearEndDate", "Decade", each Text.From(Number.IntegerDivide([Year], 10) * 10) & "s", type text),
				                #"Added FiveYearBand" = Table.AddColumn(#"Added Decade", "FiveYearBand", each Text.From(Number.IntegerDivide([Year], 5) * 5) & "-" & Text.From(Number.IntegerDivide([Year], 5) * 5 + 4), type text),
				                #"Added IsLatestYear" = Table.AddColumn(#"Added FiveYearBand", "IsLatestYear", each if [Year] = EndYear then 1 else 0, Int64.Type),
				                #"Added IsLast10Years" = Table.AddColumn(#"Added IsLatestYear", "IsLast10Years", each if [Year] >= EndYear - 9 then 1 else 0, Int64.Type),
				                #"Added IsLast5Years" = Table.AddColumn(#"Added IsLast10Years", "IsLast5Years", each Text.From(Number.IntegerDivide([Year], 5) * 5) & "-" & Text.From(Number.IntegerDivide([Year], 5) * 5 + 4), type text),
				                #"Added EconomicEra" = Table.AddColumn(#"Added IsLast5Years", "EconomicEra", each Text.From(Number.IntegerDivide([Year], 10) * 10) & "s", type text)
				            in
				                #"Added EconomicEra"

	annotation PBI_ResultType = Table

