table Countries
	lineageTag: 80e9076f-dcf4-4957-b296-0c195cad673d

	column CountryISO3
		dataType: string
		lineageTag: e441785a-5117-4b7a-b003-28b6fb57889c
		summarizeBy: none
		sourceColumn: CountryISO3

		annotation SummarizationSetBy = Automatic

	column CountryISO2
		dataType: string
		lineageTag: 2fa4924d-89e1-4c26-92ab-a21f298c15be
		summarizeBy: none
		sourceColumn: CountryISO2

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 12026973-a1bd-48e3-9423-d97f8a16de1d
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column CapitalCity
		dataType: string
		lineageTag: cc6625ed-e5a7-442e-af21-301216906259
		summarizeBy: none
		sourceColumn: CapitalCity

		annotation SummarizationSetBy = Automatic

	column CountryLong
		dataType: double
		lineageTag: 330abc51-b899-42b9-8484-f32457d2e42c
		summarizeBy: none
		sourceColumn: CountryLong

		annotation SummarizationSetBy = Automatic

	column CountryLat
		dataType: double
		lineageTag: 6fcd9871-5a6c-48fc-8906-0a289149e8a4
		summarizeBy: none
		sourceColumn: CountryLat

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 2d5b2b39-d4c7-48b5-811c-6fae13e6d45a
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column IncomeGroup
		dataType: string
		lineageTag: 8852d768-ed7c-4264-a1aa-d747b2440cec
		summarizeBy: none
		sourceColumn: IncomeGroup

		annotation SummarizationSetBy = Automatic

	column LendingType
		dataType: string
		lineageTag: 3220889e-b084-44f8-857d-a9cb0d42cc86
		summarizeBy: none
		sourceColumn: LendingType

		annotation SummarizationSetBy = Automatic

	column CountryType
		dataType: string
		lineageTag: 9c43f287-72fd-496c-9e51-6c4f1404dbd1
		summarizeBy: none
		sourceColumn: CountryType

		annotation SummarizationSetBy = Automatic

	column CountryPoint
		dataType: string
		lineageTag: e5411d34-fe5a-459a-8f8a-4aba6add54fd
		summarizeBy: none
		sourceColumn: CountryPoint

		annotation SummarizationSetBy = Automatic

	column %REGION_ACCESS
		dataType: string
		lineageTag: b84877bc-120d-42bb-95a4-7030b5547459
		summarizeBy: none
		sourceColumn: '%REGION_ACCESS'

		annotation SummarizationSetBy = Automatic

	column IncomeRank
		dataType: string
		lineageTag: b7ff05b2-6796-46cc-ae11-1e70c85772cd
		summarizeBy: none
		sourceColumn: IncomeRank

		annotation SummarizationSetBy = Automatic

	column 'Geography Drill' = 'Countries'[Region]
		dataType: string
		lineageTag: f1b8cd52-313d-43f9-9181-a42d99713f2d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Region (Countries Only)' = SWITCH(TRUE(), 'Countries'[CountryType] = "Country", 'Countries'[Region], BLANK() )
		dataType: string
		lineageTag: b2a2c21f-3469-4421-8c21-33158815ea0f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Development Drill' = 'Countries'[IncomeGroup]
		dataType: string
		lineageTag: 57460946-7d6d-425f-8d44-194fc07db436
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Lending Type' = 'Countries'[LendingType]
		dataType: string
		lineageTag: b9025ba6-e72a-42e1-ba8a-6bbd0cfd1cad
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Income Group' = SWITCH(TRUE(), 'Countries'[CountryType] = "Country", 'Countries'[IncomeGroup], BLANK() )
		dataType: string
		lineageTag: 00aaf868-2d3b-46d0-8e7e-baf416b904be
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Economy Size Band' = VAR gdp_billion = FLOOR(RELATED('Fact'[IndicatorValue]) / 1000000000, 500) VAR band = COALESCE(gdp_billion, BLANK()) RETURN IF(ISBLANK(band), BLANK(), band & " bn USD")
		dataType: string
		lineageTag: c9f03dc8-dc6c-4c83-a43b-4c9b56a70024
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Trade Position' = VAR Exports = CALCULATE(SUM(RELATED('Fact'[IndicatorValue])), RELATED('Fact'[IndicatorCode]) = "EXPORTS") VAR Imports = CALCULATE(SUM(RELATED('Fact'[IndicatorValue])), RELATED('Fact'[IndicatorCode]) = "IMPORTS") RETURN SWITCH(TRUE(), Exports > Imports * 1.1, "Strong Surplus", Exports > Imports, "Surplus", Imports > Exports * 1.1, "Strong Deficit", "Deficit" )
		dataType: string
		lineageTag: 3e7bfdc0-39ec-458a-8496-c5ac63c792cf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Countries = m
		mode: import
		source =
				let
				                // World Bank Countries API endpoint
				    BaseUrl = "https://api.worldbank.org",
				                RelPath = "v2/country",
				                QueryParams = [format = "json", per_page = "1000"],
				                // Helper to fetch a single page and return the data list
				    GetPage = (PageNumber as number) as list =>
				                    let
				                        Response = Web.Contents(BaseUrl, [
				                            RelativePath = RelPath,
				                            Query = Record.Combine({QueryParams, [page = Number.ToText(PageNumber)]})
				                        ]),
				                        Json = Json.Document(Response),
				                        Data = if List.Count(Json) > 1 then (try Json{1} otherwise {}) else {}
				                    in
				                        Data,
				                // Fetch first page to get total pages
				    FirstResponse = Web.Contents(BaseUrl, [RelativePath = RelPath, Query = QueryParams]),
				                FirstJson = Json.Document(FirstResponse),
				                Meta = if List.Count(FirstJson) > 0 then FirstJson{0} else [],
				                TotalPages = try Meta[pages] otherwise 1,
				                // Fetch all pages and combine
				    AllData = (try List.Combine(List.Transform({1..TotalPages}, each GetPage(_))) otherwise Table.Combine(List.Transform({1..TotalPages}, each GetPage(_)))),
				                CountriesRaw = (if Value.Is(AllData, type table) then AllData else Table.FromRecords(AllData)),
				                // Expand nested fields: region, adminregion, incomeLevel, lendingType
				    ExpandRegion = (try Table.ExpandRecordColumn(CountriesRaw, "region", {"value"}, {"Region"}) otherwise Table.AddColumn(Table.RemoveColumns(CountriesRaw, {"Region"}, MissingField.Ignore), "Region", each null)),
				                ExpandAdminRegion = (try Table.ExpandRecordColumn(ExpandRegion, "adminregion", {"value"}, {"AdminRegion"}) otherwise Table.AddColumn(Table.RemoveColumns(ExpandRegion, {"AdminRegion"}, MissingField.Ignore), "AdminRegion", each null)),
				                ExpandIncomeLevel = (try Table.ExpandRecordColumn(ExpandAdminRegion, "incomeLevel", {"value"}, {"IncomeGroup"}) otherwise Table.AddColumn(Table.RemoveColumns(ExpandAdminRegion, {"IncomeGroup"}, MissingField.Ignore), "IncomeGroup", each null)),
				                ExpandLendingType = (try Table.ExpandRecordColumn(ExpandIncomeLevel, "lendingType", {"value"}, {"LendingType"}) otherwise Table.AddColumn(Table.RemoveColumns(ExpandIncomeLevel, {"LendingType"}, MissingField.Ignore), "LendingType", each null)),
				                // Rename and select columns to match Qlik output
				    Renamed = Table.RenameColumns(ExpandLendingType, {{"id", "CountryISO3"}, {"iso2Code", "CountryISO2"}, {"name", "Country"}, {"capitalCity", "CapitalCity"}, {"longitude", "CountryLong"}, {"latitude", "CountryLat"}}),
				                // Add CountryType: 'Aggregate' if Region is empty or 'Aggregates', else 'Country'
				    AddCountryType = Table.AddColumn(Table.RemoveColumns(Renamed, {"CountryType"}, MissingField.Ignore), "CountryType", each if Text.Length(Text.Trim([Region])) = 0 or [Region] = "Aggregates" then "Aggregate" else "Country"),
				                // Add CountryPoint: POINT(long lat) if both are numbers
				    AddCountryPoint = Table.AddColumn(Table.RemoveColumns(AddCountryType, {"CountryPoint"}, MissingField.Ignore), "CountryPoint", each if Value.Is([CountryLat], type number) and Value.Is([CountryLong], type number) then "POINT(" & Number.ToText([CountryLong]) & " " & Number.ToText([CountryLat]) & ")" else null),
				                // Add %REGION_ACCESS: upper case of Region
				    AddRegionAccess = Table.AddColumn(Table.RemoveColumns(AddCountryPoint, {"%REGION_ACCESS"}, MissingField.Ignore), "%REGION_ACCESS", each Text.Upper([Region])),
				                // Add IncomeRank: banding by IncomeGroup
				    AddIncomeRank = Table.AddColumn(Table.RemoveColumns(AddRegionAccess, {"IncomeRank"}, MissingField.Ignore), "IncomeRank", each
				                    if [CountryType] = "Aggregate" then "Aggregate" else
				                    if [IncomeGroup] = "High income" then "1. High" else
				                    if [IncomeGroup] = "Upper middle income" then "2. Upper Middle" else
				                    if [IncomeGroup] = "Lower middle income" then "3. Lower Middle" else
				                    if [IncomeGroup] = "Low income" then "4. Low" else "5. Unclassified"
				                ),
				                // Final column selection and types
				    Final = Table.TransformColumnTypes(List.Accumulate({"CountryISO3", "CountryISO2", "Country", "CapitalCity", "CountryLong", "CountryLat", "Region", "IncomeGroup", "LendingType", "CountryType", "CountryPoint", "%REGION_ACCESS", "IncomeRank"}, Table.SelectColumns(AddIncomeRank, {"CountryISO3", "CountryISO2", "Country", "CapitalCity", "CountryLong", "CountryLat", "Region", "IncomeGroup", "LendingType", "CountryType", "CountryPoint", "%REGION_ACCESS", "IncomeRank"}, MissingField.Ignore), (state, col) => if Table.HasColumns(state, col) then state else Table.AddColumn(state, col, each null)), {
				                        {"CountryISO3", type text},
				                        {"CountryISO2", type text},
				                        {"Country", type text},
				                        {"CapitalCity", type text},
				                        {"CountryLong", type number},
				                        {"CountryLat", type number},
				                        {"Region", type text},
				                        {"IncomeGroup", type text},
				                        {"LendingType", type text},
				                        {"CountryType", type text},
				                        {"CountryPoint", type text},
				                        {"%REGION_ACCESS", type text},
				                        {"IncomeRank", type text}
				                    })
				            in
				                Final

	annotation PBI_ResultType = Table

