table Drivers
	lineageTag: eafe5de3-6495-4d05-9b8b-c4ebf7ba7b53

	measure 'Total Drivers' = DISTINCTCOUNT('Drivers'[driver_id])
		lineageTag: 5e359fb1-919a-4b0b-ac6a-113c038a9711

	column driver_id
		dataType: string
		lineageTag: 245c33eb-f537-4c6d-a253-a38fe806b054
		summarizeBy: none
		sourceColumn: driver_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 174f1cfb-6d63-4600-a0d4-152c15ccf165
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: bf89fc59-f35f-4df4-8453-dad5b073b3cf
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column hire_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 13646051-3406-44c3-b5b1-9ac1d0181b9b
		summarizeBy: none
		sourceColumn: hire_date

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column termination_date
		dataType: dateTime
		formatString: General Date
		lineageTag: dacfd02f-1860-44ef-a4bd-6dda46c8cf57
		summarizeBy: none
		sourceColumn: termination_date

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column license_number
		dataType: string
		lineageTag: 35c79b9c-6066-43f1-a8ae-821c63813d17
		summarizeBy: none
		sourceColumn: license_number

		annotation SummarizationSetBy = Automatic

	column license_state
		dataType: string
		lineageTag: 93050201-d779-4d4d-97cb-0371e2b2168f
		summarizeBy: none
		sourceColumn: license_state

		annotation SummarizationSetBy = Automatic

	column date_of_birth
		dataType: dateTime
		formatString: General Date
		lineageTag: 98ffad57-28c9-4f93-9f79-a4d5fbe30727
		summarizeBy: none
		sourceColumn: date_of_birth

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column home_terminal
		dataType: string
		lineageTag: 0db7c6f6-9819-4801-9b71-bc3095ca4930
		summarizeBy: none
		sourceColumn: home_terminal

		annotation SummarizationSetBy = Automatic

	column employment_status
		dataType: string
		lineageTag: dc44da85-f852-467d-a5bc-7f05728fed1f
		summarizeBy: none
		sourceColumn: employment_status

		annotation SummarizationSetBy = Automatic

	column cdl_class
		dataType: string
		lineageTag: a0a96cdc-5d59-480d-bfde-220939f9a7a2
		summarizeBy: none
		sourceColumn: cdl_class

		annotation SummarizationSetBy = Automatic

	column years_experience
		dataType: int64
		formatString: 0
		lineageTag: 010c7c2d-e3c4-4b74-b243-c6e63bde33f9
		summarizeBy: none
		sourceColumn: years_experience

		annotation SummarizationSetBy = Automatic

	column DriverName
		dataType: string
		lineageTag: 0e83128c-5326-4a4d-bff8-9cda2e0b1167
		summarizeBy: none
		sourceColumn: DriverName

		annotation SummarizationSetBy = Automatic

	column Driver = 'Drivers'[first_name] & " " & 'Drivers'[last_name]
		dataType: string
		lineageTag: 6448f762-45bc-4216-a466-a3699fa86eac
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'HOME_TERMINAL 2'
		dataType: string
		lineageTag: 448b515f-81bd-4e3e-a636-8bcd233d298b
		summarizeBy: none
		sourceColumn: HOME_TERMINAL

		annotation SummarizationSetBy = Automatic

	partition Drivers = m
		mode: import
		source =
				let
				                Source = AmazonRedshift.Database("fleetvision-wg.881226714470.ap-southeast-2.redshift-serverless.amazonaws.com:5439", "dev"),
				                Schema = Source{[Name="fleetvision",Kind="Schema"]}[Data],
				                Navigation = Schema{[Name="drivers"]}[Data],
				                #"Added DriverName" = Table.AddColumn(Navigation, "DriverName", each Text.Trim([first_name] & " " & [last_name]), type text),
				                #"Added HOME_TERMINAL" = Table.AddColumn(#"Added DriverName", "HOME_TERMINAL", each Text.Upper(Text.Trim([home_terminal])), type text)
				            in
				                #"Added HOME_TERMINAL"

	annotation PBI_ResultType = Table

