table Trailers
	lineageTag: 49021e81-7cd5-42a0-8049-a1b4a538b0cf

	measure 'Active Trailers' = CALCULATE(DISTINCTCOUNT('Trailers'[trailer_id]), 'Trailers'[trailer_status] = "Active")
		lineageTag: 26510a99-96ea-463f-b899-c23c7fd1a712

	column trailer_id
		dataType: string
		lineageTag: 0df2b6c9-1569-41b3-8301-e424012c435a
		summarizeBy: none
		sourceColumn: trailer_id

		annotation SummarizationSetBy = Automatic

	column trailer_number
		dataType: int64
		formatString: 0
		lineageTag: 4cdb8dd3-c520-4b56-8c0e-7c3436e5bbc3
		summarizeBy: none
		sourceColumn: trailer_number

		annotation SummarizationSetBy = Automatic

	column trailer_type
		dataType: string
		lineageTag: 81cb444a-0f6b-44cf-877a-20b0080042cf
		summarizeBy: none
		sourceColumn: trailer_type

		annotation SummarizationSetBy = Automatic

	column length_feet
		dataType: int64
		formatString: 0
		lineageTag: e24e1be7-5fb2-40b5-a4ac-f679e33ca7b3
		summarizeBy: none
		sourceColumn: length_feet

		annotation SummarizationSetBy = Automatic

	column trailer_model_year
		dataType: int64
		formatString: 0
		lineageTag: ae1691da-3bf1-4be8-a0e1-f80fbc8b25fc
		summarizeBy: none
		sourceColumn: trailer_model_year

		annotation SummarizationSetBy = Automatic

	column trailer_vin
		dataType: string
		lineageTag: e9d3f9e0-ce1e-4205-a3b9-66299854826c
		summarizeBy: none
		sourceColumn: trailer_vin

		annotation SummarizationSetBy = Automatic

	column trailer_acquisition_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7f6052bd-4243-4fd6-b8da-f47d65a94809
		summarizeBy: none
		sourceColumn: trailer_acquisition_date

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column trailer_status
		dataType: string
		lineageTag: 6e7d3789-761f-40c1-9bd0-3706b3428d98
		summarizeBy: none
		sourceColumn: trailer_status

		annotation SummarizationSetBy = Automatic

	column current_location
		dataType: string
		lineageTag: 2de6d991-4234-4f3b-9861-eb537893d1bd
		summarizeBy: none
		sourceColumn: current_location

		annotation SummarizationSetBy = Automatic

	partition Trailers = m
		mode: import
		source =
				let
				                Source = AmazonRedshift.Database("fleetvision-wg.881226714470.ap-southeast-2.redshift-serverless.amazonaws.com:5439", "dev"),
				                Schema = Source{[Name="fleetvision",Kind="Schema"]}[Data],
				                Navigation = Schema{[Name="trailers"]}[Data],
				                #"Renamed Columns" = Table.RenameColumns(Navigation, {{"model_year", "trailer_model_year"}, {"vin", "trailer_vin"}, {"acquisition_date", "trailer_acquisition_date"}, {"status", "trailer_status"}}, MissingField.Ignore)
				            in
				                #"Renamed Columns"

	annotation PBI_ResultType = Table

