table Years
	lineageTag: 9730e5a2-6846-4f82-a0f7-527fb21dd9ac

	measure 'Projected GDP' = [vGDPLatest] * POWER(1 + ([vGDPCAGR10] + DIVIDE([vGrowthScenarioPct], 100, BLANK())),[vProjectionYears])
		lineageTag: 0874aedf-d1ae-4e55-8f7a-76cbee2c1fce

	measure 'Dynamic Indicator' = VAR SelectedDynamicMeasure =[DynamicMeasure Parameter]) RETURN SWITCH(SelectedDynamicMeasure, BLANK())
		lineageTag: 3ac525de-33f4-4bbe-927c-6a2c9c717035

	measure 'GDP Growth %' = DIVIDE([vGDPGrowth], 100, BLANK())
		formatString: 0.0%
		lineageTag: 88c424a8-0fb0-40a2-b14d-441c338732a6

	measure 'GDP Last Year' = [vGDPLY]
		lineageTag: 42284721-4bff-4e9e-ac59-8b549c570cfb

	measure 'Inflation % (GDP-weighted)' = DIVIDE([vInflationWeighted], 100, BLANK())
		formatString: 0.0%
		lineageTag: 6fad443a-92c8-4a1b-83f9-3d9a5164356f

	measure 'GDP Latest Year in US$ trillions' = DIVIDE([vGDPLatest], 1000000000000, BLANK())
		lineageTag: 5dac7ee0-1b18-43f5-80a7-ab3dc7aea137

	measure 'Inflation %' = DIVIDE([vInflation], 100, BLANK())
		formatString: 0.0%
		lineageTag: 45e076d3-b62b-49a0-a2de-ba2cbcda0ba9

	measure 'GDP YoY %' = VAR _CurrentYear = MAX('Years'[Year]) VAR _CurrentGDP = CALCULATE(SUM('Fact'[GDPGrowthValue]), 'Fact'[Year] = _CurrentYear) VAR _PriorGDP = CALCULATE(SUM('Fact'[GDPGrowthValue]), 'Fact'[Year] = _CurrentYear - 1) RETURN DIVIDE(_CurrentGDP - _PriorGDP, _PriorGDP, BLANK())
		formatString: 0.0%
		lineageTag: 4d632c4a-3ef0-4c63-ab8e-abecff377c43

	measure 'Rolling 5-Year Avg Growth' = DIVIDE(AVERAGEX(TOPN(5, ALL('Years'), 'Years'[Year], DESC),[vGDPGrowth]), 100, BLANK())
		lineageTag: 4ac0d8a7-89d4-442a-8d99-8ce9f8c2e252

	measure 'Unemployment %' = DIVIDE([vUnemployment], 100, BLANK())
		formatString: 0.0%
		lineageTag: e2fd9e96-c116-45f9-93c7-95b5bce84211

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 35e825af-9e2b-4aec-86f3-2175e006912d
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Time Drill' = 'Years'[Decade]
		dataType: string
		lineageTag: 01b058de-4621-47c4-849e-a377e07acf7c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Years = m
		mode: import
		source =
				let
				                StartYear = 1990,
				                EndYear = 2024,
				                Count = EndYear - StartYear + 1,
				                YearList = List.Numbers(StartYear, Count),
				                #"Converted to Table" = Table.FromList(YearList, Splitter.SplitByNothing(), {"Year"}, null),
				                #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table", {{"Year", Int64.Type}}),
				                #"Added YearEndDate" = Table.AddColumn(#"Changed Type", "YearEndDate", each #date([Year], 12, 31), type date),
				                #"Added Decade" = Table.AddColumn(#"Added YearEndDate", "Decade", each Text.From(Number.IntegerDivide([Year], 10) * 10) & "s", type text),
				                #"Added FiveYearBand" = Table.AddColumn(#"Added Decade", "FiveYearBand", each Text.From(Number.IntegerDivide([Year], 5) * 5) & "-" & Text.From(Number.IntegerDivide([Year], 5) * 5 + 4), type text),
				                #"Added IsLatestYear" = Table.AddColumn(#"Added FiveYearBand", "IsLatestYear", each if [Year] = EndYear then 1 else 0, Int64.Type),
				                #"Added IsLast10Years" = Table.AddColumn(#"Added IsLatestYear", "IsLast10Years", each if [Year] >= EndYear - 9 then 1 else 0, Int64.Type),
				                #"Added IsLast5Years" = Table.AddColumn(#"Added IsLast10Years", "IsLast5Years", each Text.From(Number.IntegerDivide([Year], 5) * 5) & "-" & Text.From(Number.IntegerDivide([Year], 5) * 5 + 4), type text),
				                #"Added EconomicEra" = Table.AddColumn(#"Added IsLast5Years", "EconomicEra", each Text.From(Number.IntegerDivide([Year], 10) * 10) & "s", type text)
				            in
				                #"Added EconomicEra"

	annotation PBI_ResultType = Table

