table Years
    lineageTag: 218d7ddb-d2fd-4d35-a042-584102d8f7df
    annotation PBI_ResultType = Table
    column Year
        sourceColumn: Year
        dataType: int64
        lineageTag: 7cc01e88-3053-410c-8f21-d117b30b1038
        summarizeBy: none
        formatString: 0
        annotation SummarizationSetBy = Automatic

    column 'Time Drill' = 'Years'[Decade]
        type: calculated
        dataType: string
        lineageTag: 4e7be054-ec42-43f7-9364-409d4796b3d1
        summarizeBy: none
        annotation SummarizationSetBy = Automatic

    partition Years = m
        mode: import
        source =
            let
                            StartYear = 1990,
                            EndYear = 2024,
                            Count = EndYear - StartYear + 1,
                            YearList = List.Numbers(StartYear, Count),
                            #"Converted to Table" = Table.FromList(YearList, Splitter.SplitByNothing(), {"Year"}, null),
                            #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table", {{"Year", Int64.Type}}),
                            #"Added YearEndDate" = Table.AddColumn(#"Changed Type", "YearEndDate", each #date([Year], 12, 31), type date),
                            #"Added Decade" = Table.AddColumn(#"Added YearEndDate", "Decade", each Text.From(Number.IntegerDivide([Year], 10) * 10) & "s", type text),
                            #"Added FiveYearBand" = Table.AddColumn(#"Added Decade", "FiveYearBand", each Text.From(Number.IntegerDivide([Year], 5) * 5) & "-" & Text.From(Number.IntegerDivide([Year], 5) * 5 + 4), type text),
                            #"Added IsLatestYear" = Table.AddColumn(#"Added FiveYearBand", "IsLatestYear", each if [Year] = EndYear then 1 else 0, Int64.Type),
                            #"Added IsLast10Years" = Table.AddColumn(#"Added IsLatestYear", "IsLast10Years", each if [Year] >= EndYear - 9 then 1 else 0, Int64.Type),
                            #"Added IsLast5Years" = Table.AddColumn(#"Added IsLast10Years", "IsLast5Years", each Text.From(Number.IntegerDivide([Year], 5) * 5) & "-" & Text.From(Number.IntegerDivide([Year], 5) * 5 + 4), type text),
                            #"Added EconomicEra" = Table.AddColumn(#"Added IsLast5Years", "EconomicEra", each Text.From(Number.IntegerDivide([Year], 10) * 10) & "s", type text)
                        in
                            #"Added EconomicEra"
